[package]
name = "nac-pxeserver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
clap = { version = "4.5.18", features = ["derive"] }
tftpd = "0.3.1"
tide = "0.16.0"
